server:
    port: 13166

database:
    driver: mysql
    host: "127.0.0.1"
    port: 3306
    username: root
    password: root
    dbname: dyshop
    max_idle_conns: 10
    max_open_conns: 100
    conn_max_lifetime: 3600

log:
  level: debug  # ENV LOG_LEVEL

etcd:
    endpoints: "127.0.0.1:2379" # Etcd 节点地址
    prefix: 
        this: "/services/product" # 服务注册前缀

service:
    id: "prodcut-service-1" # 服务实例ID
    address: "127.0.0.1:13166" # 服务实例地址

prometheus: "/services/prometheus"

metrics:
  host: "127.0.0.1"
  port: 13167 # 服务实例监控端口
