server:
  port: 14166

database:
  driver: mysql
  host: "127.0.0.1"
  port: 3306
  username: root
  password: root
  dbname: cart_db
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600

log:
  level: debug

etcd:
  endpoint: "127.0.0.1:2379" # ENV ETCD_ENDPOINTS
  prefix: "/services/cart"  # 服务注册前缀

service:
  id: "cart-service-1"     # 服务实例ID
  address: "127.0.0.1:14166" # ENV SERVICE_ADDRESS

prometheus: "/services/prometheus"

metrics:
  host: "127.0.0.1"
  port: 14167 # 服务实例监控端口