server:
  port: 14166

etcd:
  endpoints:
    - "127.0.0.1:2379"       # Etcd 节点地址
  prefix: "/services/cart"  # 服务注册前缀

services:
  - id: "cart-service-1"     # 服务实例ID
    address: "127.0.0.1:14166" # 服务实例地址

mysql:
  dsn: "root:root@tcp(127.0.0.1:3306)/cart_db?charset=utf8mb4&parseTime=True&loc=Local"