global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "services"
    metrics_path: "/metrics"

    file_sd_configs:
      - files:
        - /etc/prometheus/targets/*.json
        refresh_interval: 5s