services:
  etcd:
    image: docker.io/bitnami/etcd:3.5
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - 2379:2379
      - 2380:2380
  mysql:
    image: "mysql:latest"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  prometheus:
    image: jiny14/mypromethues:latest
    depends_on:
      - etcd
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      # - ./config/targets:/etc/prometheus/targets
    ports:
      - "9090:9090"
      - "9091:9091"
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
  user:
    image: jiny14/dyshop-user:latest
    depends_on:
      - mysql
      - etcd
      - prometheus
    ports:
      - "12166:12166"
    environment:
      - LOG_LEVEL=info
      - DATABASE_HOST=mysql
      - ETCD_ENDPOINTS=etcd:2379
      - METRICS_HOST=user
      - SERVICE_ID=user-service-1
      - SERVICE_ADDRESS=user:12166
  user2:
    image: jiny14/dyshop-user:latest
    depends_on:
      - mysql
      - etcd
      - prometheus
    ports:
      - "12166:12166"
    environment:
      - LOG_LEVEL=info
      - DATABASE_HOST=mysql
      - ETCD_ENDPOINTS=etcd:2379
      - METRICS_HOST=user2
      - SERVICE_ID=user-service-2
      - SERVICE_ADDRESS=user2:12166