server:
  port: 11166

etcd:
  endpoints:
    - "127.0.0.1:2379"       # Etcd 节点地址
  prefix: "/services/auth"  # 服务注册前缀

services:
  - id: "auth-service-1"     # 服务实例ID
    address: "127.0.0.1:11166" # 服务实例地址