server:
  port: 10166
  mode: development

database:
  driver: mysql
  host: localhost
  port: 3306
  username: root
  password: root
  dbname: user
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

log:
  level: debug
  path: logs/app.log
  maxsize: 100
  maxage: 7
  maxbackups: 10

etcd:
  endpoints: "127.0.0.1:2379" # Etcd 节点地址
  prefix:
    auth: "/services/auth"
    user: "/services/user"
    cart: "/services/cart"
    product: "/services/product"
    order: "/services/order"
    checkout: "/services/checkout"
    payment: "/services/payment"
    this: "/services/frontend"
