services:
  mysql:
    image: "mysql:8.0"
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "dyshop"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "123456"
    volumes:
      - mysql_data:/var/lib/mysql  # 持久化数据卷
volumes:
  mysql_data: