etcd:
  endpoint: "127.0.0.1:2379" # ENV ETCD_ENDPOINT
  prefix: "/services/prometheus"

service:
  id: "prometheus-service-1" # ENV SERVICE_ID
  address: "127.0.0.1:9091" # ENV SERVICE_ADDRESS

targets:
  path: "/etc/prometheus/targets"  # promethus yml file_sd_configs

log:
  level: "debug"  # ENV LOG_LEVEL