server:
  port: 12166
  mode: development
  start_time: "2025-02-14"
  machine_id: 1

database:
  driver: mysql
  host: "127.0.0.1" # ENV DATABASE_HOST
  port: 3306
  username: root
  password: root
  dbname: dyshop
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

log:
  level: debug  # ENV LOG_LEVEL
  path: logs/app.log
  maxsize: 100
  maxage: 7
  maxbackups: 10

etcd:
  endpoints: "127.0.0.1:2379" # ENV ETCD_ENDPOINT
  prefix: 
    this: "/services/user"
    auth: "/services/auth"

service:
  id: "user-service-1" # ENV SERVICE_ID
  address: "127.0.0.1:12166" # ENV SERVICE_ADDRESS

prometheus: "/services/prometheus"

metrics:
  host: "127.0.0.1" # ENV METRICS_HOST
  port: 12168