server:
  port: 12166
  mode: development

database:
  driver: mysql
  host: "127.0.0.1"
  port: 3306
  username: root
  password: 123456
  dbname: dyshop
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

log:
  level: debug
  filename: ./logs/app.log
  maxsize: 100
  maxage: 7
  maxbackups: 10